[package]
name = "ChronodriveCycleOfSteel"
version = "0.1.0"
edition = "2021"

[dependencies]
piston = "1.0.0"
pistoncore-glutin_window = "0.72.0"
piston2d-graphics = "0.45.0"
piston2d-opengl_graphics = "0.86.0"
piston_window = "0.132.0"
rand = "0.8.5"